/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntercomHostIdRouteImport } from './routes/intercom-host.$id'
import { Route as DoorbellIdRouteImport } from './routes/doorbell.$id'
import { Route as DeviceIdRouteImport } from './routes/device.$id'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntercomHostIdRoute = IntercomHostIdRouteImport.update({
  id: '/intercom-host/$id',
  path: '/intercom-host/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoorbellIdRoute = DoorbellIdRouteImport.update({
  id: '/doorbell/$id',
  path: '/doorbell/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceIdRoute = DeviceIdRouteImport.update({
  id: '/device/$id',
  path: '/device/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/device/$id': typeof DeviceIdRoute
  '/doorbell/$id': typeof DoorbellIdRoute
  '/intercom-host/$id': typeof IntercomHostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/device/$id': typeof DeviceIdRoute
  '/doorbell/$id': typeof DoorbellIdRoute
  '/intercom-host/$id': typeof IntercomHostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/device/$id': typeof DeviceIdRoute
  '/doorbell/$id': typeof DoorbellIdRoute
  '/intercom-host/$id': typeof IntercomHostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/join'
    | '/device/$id'
    | '/doorbell/$id'
    | '/intercom-host/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/join'
    | '/device/$id'
    | '/doorbell/$id'
    | '/intercom-host/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/join'
    | '/device/$id'
    | '/doorbell/$id'
    | '/intercom-host/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  JoinRoute: typeof JoinRoute
  DeviceIdRoute: typeof DeviceIdRoute
  DoorbellIdRoute: typeof DoorbellIdRoute
  IntercomHostIdRoute: typeof IntercomHostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intercom-host/$id': {
      id: '/intercom-host/$id'
      path: '/intercom-host/$id'
      fullPath: '/intercom-host/$id'
      preLoaderRoute: typeof IntercomHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doorbell/$id': {
      id: '/doorbell/$id'
      path: '/doorbell/$id'
      fullPath: '/doorbell/$id'
      preLoaderRoute: typeof DoorbellIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/$id': {
      id: '/device/$id'
      path: '/device/$id'
      fullPath: '/device/$id'
      preLoaderRoute: typeof DeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  JoinRoute: JoinRoute,
  DeviceIdRoute: DeviceIdRoute,
  DoorbellIdRoute: DoorbellIdRoute,
  IntercomHostIdRoute: IntercomHostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
